name: Cepta API Documentation
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Cepta Build Microservice
    if: github.ref == 'refs/heads/main'
    uses: TurnerWhittman/actions-workflow/.github/workflows/frontend-build.yml@main
    with:
      ECR_REPOSITORY: "twpay-api-documentation"
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  deploy:
    name: Cepta Deploy Microservice
    needs: build
    if: github.ref == 'refs/heads/main'
    uses: TurnerWhittman/actions-workflow/.github/workflows/release.yml@main
    with:
      SERVICE: apidocs
      GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
      GITHUB_ACTOR: ${{ github.actor }}
      GITHUB_REF_NAME: ${{ github.ref_name }}
      GITHUB_RUN_NUMBER: ${{ github.run_number }}
      CI_COMMIT_TITLE: ${{ github.event.head_commit.message }}
    secrets:
      USERNAME: ${{ secrets.USERNAME }}
      TOKEN: ${{ secrets.TOKEN }}